### ISSUE TITLE
不能用啊

### ISSUE THREAD

**Issue by zhiao6** [365360171/qlwxyd#1]
找到[yuedu1] 变量 2个账号
TypeError: Cannot read properties of null (reading 'jump')
    at gethost (/ql/data/scripts/jiasai007_wxyd/wx_yd.js:275:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /ql/data/scripts/jiasai007_wxyd/wx_yd.js:252:13
获取到newurl：http://m.uywpbfv.work/

=========== 账号[1]  开始阅读文章 ===========

TypeError: Cannot read properties of null (reading 'data')
    at UserInfo.withdrawal (/ql/data/scripts/jiasai007_wxyd/wx_yd.js:173:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserInfo.task (/ql/data/scripts/jiasai007_wxyd/wx_yd.js:236:13)
    at async /ql/data/scripts/jiasai007_wxyd/wx_yd.js:255:17

=========== 账号[2]  开始阅读文章 ===========

TypeError: Cannot read properties of null (reading 'data')
    at UserInfo.withdrawal (/ql/data/scripts/jiasai007_wxyd/wx_yd.js:173:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async UserInfo.task (/ql/data/scripts/jiasai007_wxyd/wx_yd.js:236:13)
    at async /ql/data/scripts/jiasai007_wxyd/wx_yd.js:255:17

**Comment by 365360171** [comment]
重新抓ck试试

**Comment by zhiao6** [comment]
> 

不太行，你的现在还可以用吗

**Comment by 365360171** [comment]
> > 
> 
> 不太行，你的现在还可以用吗

可以的

**Comment by 365360171** [comment]
> > 
> 
> 不太行，你的现在还可以用吗

可以的
